#db yml configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: AirQ_development
  username: postgres
  password: admin

 
test:
  <<: *default
  database: AirQ_test

# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: AirQ_production
  username: AirQ
  password: <%= ENV['AIRQ_DATABASE_PASSWORD'] %>
